import React, { useMemo, useState } from "react";
import { Check, ExternalLink, MapPin, Pencil, Plus, Search, Ticket, Trash2, X } from "lucide-react";
import type { ActivityItem } from "../types";
import { AttachmentListControl } from "./AttachmentListControl";

interface Props { activities: ActivityItem[]; onUpdateActivity: (item: ActivityItem) => void; onAddActivity: (item: ActivityItem) => void; onDeleteActivity: (id: string) => void; }
const blank = (): ActivityItem => ({ id: `activity-${Date.now()}`, name: "", date: "", location: "", description: "", notes: "", priceEur: 0, bookingRef: "", provider: "", website: "", booked: false, paid: false });
const dateLabel = (value?: string) => value ? new Intl.DateTimeFormat("nl-NL", { weekday: "short", day: "numeric", month: "long" }).format(new Date(`${value}T12:00:00`)) : "Datum nog niet ingevuld";

export const ActiviteitenView: React.FC<Props> = ({ activities, onUpdateActivity, onAddActivity, onDeleteActivity }) => {
  const [search, setSearch] = useState(""); const [country, setCountry] = useState("Alle landen"); const [bookedOnly, setBookedOnly] = useState(false); const [draft, setDraft] = useState<ActivityItem>(); const [isNew, setIsNew] = useState(false);
  const countries = useMemo(() => ["Alle landen", ...Array.from(new Set(activities.map((x) => x.land || x.country).filter(Boolean) as string[])).sort()], [activities]);
  const filtered = useMemo(() => activities.filter((x) => country === "Alle landen" || (x.land || x.country) === country).filter((x) => !bookedOnly || x.booked || x.geboekt).filter((x) => `${x.name || x.title} ${x.location || x.plaats || ""} ${x.notes || ""}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => String(a.date || a.datum || "9999").localeCompare(String(b.date || b.datum || "9999"))), [activities, bookedOnly, country, search]);
  const updateStatus = (item: ActivityItem, key: "booked" | "paid") => onUpdateActivity({ ...item, [key]: !Boolean(item[key]), [key === "booked" ? "geboekt" : "betaald"]: !Boolean(item[key]) });
  const save = () => { if (!draft || !(draft.name || draft.title)?.trim()) return; const item = { ...draft, name: draft.name || draft.title, title: draft.name || draft.title, datum: draft.date, plaats: draft.location, bookingReference: draft.bookingRef, boekingsnummer: draft.bookingRef, geboekt: draft.booked, betaald: draft.paid }; isNew ? onAddActivity(item) : onUpdateActivity(item); setDraft(undefined); };
  return <div className="space-y-5">
    <header className="flex flex-col gap-4 rounded-3xl bg-gradient-to-br from-[#174A7E] via-[#176986] to-[#0f9ca8] p-5 text-white shadow-lg sm:flex-row sm:items-end sm:justify-between sm:p-7"><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-200">Plannen en boeken</p><h1 className="mt-1 flex items-center gap-2 text-3xl font-black"><Ticket className="h-7 w-7"/>Activiteiten</h1></div><button onClick={() => { setDraft(blank()); setIsNew(true); }} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-white px-4 text-sm font-black text-[#174A7E]"><Plus className="h-4 w-4"/>Activiteit toevoegen</button></header>
    <section className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm md:grid-cols-[1fr_auto_auto] dark:border-slate-800 dark:bg-slate-900"><label className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Zoek activiteit of plaats" className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50 pl-9 pr-3 text-sm dark:border-slate-700 dark:bg-slate-800"/></label><select value={country} onChange={(e) => setCountry(e.target.value)} className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm font-bold dark:border-slate-700 dark:bg-slate-800">{countries.map((x) => <option key={x}>{x}</option>)}</select><button onClick={() => setBookedOnly(!bookedOnly)} className={`h-11 rounded-xl px-4 text-sm font-black ${bookedOnly ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200"}`}>Alleen geboekt</button></section>
    <div className="grid gap-4 xl:grid-cols-2">{filtered.map((item) => <article key={item.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-[#1593a3]">{dateLabel(item.date || item.datum)}</p><h2 className="mt-1 text-xl font-black">{item.name || item.title}</h2></div>{Number(item.priceEur || item.price || 0) > 0 && <span className="rounded-xl bg-[#174A7E] px-3 py-1.5 text-sm font-black text-white">€ {Number(item.priceEur || item.price).toLocaleString("nl-NL", { minimumFractionDigits: 2 })}</span>}</div>{(item.address || item.location || item.plaats) && <p className="mt-3 flex gap-2 text-sm text-slate-500"><MapPin className="h-4 w-4 shrink-0"/>{item.address || item.location || item.plaats}</p>}{(item.description || item.notes) && <p className="mt-3 whitespace-pre-line text-sm leading-6 text-slate-600 dark:text-slate-300">{item.description || item.notes}</p>}
      <div className="mt-4 flex flex-wrap gap-2"><button onClick={() => updateStatus(item, "booked")} className={`rounded-full px-3 py-1.5 text-xs font-black ${(item.booked || item.geboekt) ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{(item.booked || item.geboekt) ? <span className="flex items-center gap-1"><Check className="h-3 w-3"/>Geboekt</span> : "Nog te boeken"}</button><button onClick={() => updateStatus(item, "paid")} className={`rounded-full px-3 py-1.5 text-xs font-black ${(item.paid || item.betaald) ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-500"}`}>{(item.paid || item.betaald) ? "✓ Betaald" : "Niet betaald"}</button>{(item.bookingRef || item.bookingReference) && <span className="rounded-full bg-violet-100 px-3 py-1.5 text-xs font-black text-violet-700">Boeking {item.bookingRef || item.bookingReference}</span>}</div>
      <div className="mt-4"><AttachmentListControl attachments={item.ticketPdfs} legacyAttachment={item.ticketPdf} label="Ticket of bevestiging" onChange={(ticketPdfs) => onUpdateActivity({ ...item, ticketPdfs, ticketPdf: ticketPdfs[0] })}/></div><div className="mt-4 flex gap-2 border-t border-slate-100 pt-4 dark:border-slate-800">{(item.website || item.ticketsUrl) && <a href={item.website || item.ticketsUrl} target="_blank" rel="noreferrer" className="flex h-10 items-center gap-1 rounded-xl bg-[#174A7E] px-3 text-xs font-black text-white"><ExternalLink className="h-3.5 w-3.5"/>Boekingslink</a>}<button onClick={() => { setDraft({ ...item, bookingRef: item.bookingRef || item.bookingReference }); setIsNew(false); }} className="ml-auto rounded-xl border p-2 text-slate-500"><Pencil className="h-4 w-4"/></button><button onClick={() => confirm("Deze activiteit verwijderen?") && onDeleteActivity(item.id)} className="rounded-xl border p-2 text-rose-600"><Trash2 className="h-4 w-4"/></button></div></article>)}</div>
    {draft && <Editor draft={draft} setDraft={setDraft} isNew={isNew} onClose={() => setDraft(undefined)} onSave={save}/>} {!filtered.length && <div className="rounded-3xl border border-dashed p-10 text-center font-black">Geen activiteiten gevonden</div>}
  </div>;
};

const Editor = ({ draft, setDraft, isNew, onClose, onSave }: { draft: ActivityItem; setDraft: (x: ActivityItem) => void; isNew: boolean; onClose: () => void; onSave: () => void }) => <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/60 p-3 sm:items-center"><div className="max-h-[92dvh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-5 dark:bg-slate-900"><div className="flex justify-between"><h2 className="text-xl font-black">{isNew ? "Activiteit toevoegen" : "Activiteit bewerken"}</h2><button onClick={onClose}><X/></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="Activiteit of excursie" value={draft.name || draft.title || ""} change={(v) => setDraft({ ...draft, name: v })} wide/><Field label="Reisdatum" type="date" value={draft.date || draft.datum || ""} change={(v) => setDraft({ ...draft, date: v })}/><Field label="Plaats" value={draft.location || draft.plaats || ""} change={(v) => setDraft({ ...draft, location: v })}/><Field label="Prijs" type="number" value={String(draft.priceEur || "")} change={(v) => setDraft({ ...draft, priceEur: Number(v) })}/><Field label="Boekingsnummer" value={draft.bookingRef || ""} change={(v) => setDraft({ ...draft, bookingRef: v })}/><Field label="Aanbieder" value={draft.provider || ""} change={(v) => setDraft({ ...draft, provider: v })}/><Field label="Boekingslink" type="url" value={draft.website || ""} change={(v) => setDraft({ ...draft, website: v })}/><Area label="Omschrijving" value={draft.description || ""} change={(v) => setDraft({ ...draft, description: v })}/><Area label="Notities" value={draft.notes || ""} change={(v) => setDraft({ ...draft, notes: v })}/><CheckField label="Geboekt" checked={Boolean(draft.booked)} change={(v) => setDraft({ ...draft, booked: v })}/><CheckField label="Betaald" checked={Boolean(draft.paid)} change={(v) => setDraft({ ...draft, paid: v })}/></div><button onClick={onSave} className="mt-5 h-12 w-full rounded-xl bg-[#174A7E] text-sm font-black text-white">Opslaan</button></div></div>;
const Field = ({ label, value, change, type = "text", wide }: { label: string; value: string; change: (v: string) => void; type?: string; wide?: boolean }) => <label className={`text-xs font-bold ${wide ? "sm:col-span-2" : ""}`}>{label}<input type={type} step={type === "number" ? ".01" : undefined} value={value} onChange={(e) => change(e.target.value)} className="mt-1 h-11 w-full rounded-xl border bg-transparent px-3 text-sm font-normal"/></label>;
const Area = ({ label, value, change }: { label: string; value: string; change: (v: string) => void }) => <label className="text-xs font-bold sm:col-span-2">{label}<textarea rows={3} value={value} onChange={(e) => change(e.target.value)} className="mt-1 w-full rounded-xl border bg-transparent p-3 text-sm font-normal"/></label>;
const CheckField = ({ label, checked, change }: { label: string; checked: boolean; change: (v: boolean) => void }) => <label className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 text-sm font-bold dark:bg-slate-800"><input type="checkbox" checked={checked} onChange={(e) => change(e.target.checked)}/>{label}</label>;
export default ActiviteitenView;
