import React, { useState } from "react";
import { CalendarDays, Clock3, Pencil, Plane, Plus, Save, Trash2, X } from "lucide-react";
import type { Flight } from "../types";
import { AttachmentListControl } from "./AttachmentListControl";

interface Props { flights?: Flight[]; onAddFlight?: (flight: Flight) => void; onUpdateFlight?: (flight: Flight) => void; onDeleteFlight?: (id: string) => void; }
const blankFlight = (): Flight => ({ id: `flight-${Date.now()}`, airline: "", flightNumber: "", fromCode: "", toCode: "", departureDate: "", arrivalDate: "", departureTime: "", arrivalTime: "", bookingReference: "", seat: "" });
const place = (flight: Flight, side: "from" | "to") => side === "from" ? flight.fromCode || flight.departureAirport || flight.fromCity || "?" : flight.toCode || flight.arrivalAirport || flight.toCity || "?";
const flightLabel = (flight: Flight) => { const airline = String(flight.airline || "").trim(); const number = String(flight.flightNumber || "").trim(); return number.toUpperCase().startsWith(airline.toUpperCase()) ? number : [airline, number].filter(Boolean).join(" "); };

export const VluchtenView: React.FC<Props> = ({ flights = [], onAddFlight, onUpdateFlight, onDeleteFlight }) => {
  const [editingId, setEditingId] = useState<string>();
  const [draft, setDraft] = useState<Flight>();
  const startAdd = () => { const flight = blankFlight(); setEditingId(flight.id); setDraft(flight); };
  const save = () => { if (!draft) return; flights.some((item) => item.id === draft.id) ? onUpdateFlight?.(draft) : onAddFlight?.(draft); setEditingId(undefined); setDraft(undefined); };
  return <div className="space-y-5">
    {(onAddFlight || onUpdateFlight) && <div className="flex justify-end"><button type="button" onClick={startAdd} className="flex min-h-11 items-center gap-2 rounded-xl bg-[#174A7E] px-4 text-sm font-black text-white"><Plus className="h-4 w-4" />Vlucht toevoegen</button></div>}
    <div className="grid gap-4 xl:grid-cols-2">{[...flights, ...(draft && !flights.some((item) => item.id === draft.id) ? [draft] : [])].map((flight) => { const editing = editingId === flight.id && draft; return <article key={flight.id} className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-5">
      <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-sky-700">{flightLabel(flight) || "Nieuwe vlucht"}</p><h2 className="mt-1 text-xl font-black">{place(flight, "from")} <span className="text-sky-500">→</span> {place(flight, "to")}</h2></div><div className="flex gap-1">{onUpdateFlight && <button type="button" onClick={() => editing ? (setEditingId(undefined), setDraft(undefined)) : (setEditingId(flight.id), setDraft({ ...flight }))} className="rounded-xl border border-slate-200 p-2 text-slate-500 dark:border-slate-700">{editing ? <X className="h-4 w-4" /> : <Pencil className="h-4 w-4" />}</button>}{onDeleteFlight && !editing && <button type="button" onClick={() => window.confirm("Deze vlucht verwijderen?") && onDeleteFlight(flight.id)} className="rounded-xl border border-slate-200 p-2 text-rose-600 dark:border-slate-700"><Trash2 className="h-4 w-4" /></button>}</div></div>
      {!editing && <><div className="mt-4 grid grid-cols-2 gap-3"><Moment label="Vertrek" date={flight.departureDate} time={flight.departureTime} /><Moment label="Aankomst" date={flight.arrivalDate || flight.departureDate} time={flight.arrivalTime} /></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><Info label="Reserveringsnummer" value={flight.bookingReference} /><Info label="Stoelen" value={flight.seat} /></div></>}
      {editing && <div className="mt-4 rounded-2xl border border-sky-200 bg-sky-50/60 p-4 dark:border-sky-900 dark:bg-sky-950/20"><div className="grid gap-3 sm:grid-cols-2"><Field label="Maatschappij" value={draft.airline || ""} onChange={(value) => setDraft({ ...draft, airline: value })} /><Field label="Vluchtnummer" value={draft.flightNumber || ""} onChange={(value) => setDraft({ ...draft, flightNumber: value })} /><Field label="Van (code)" value={draft.fromCode || ""} onChange={(value) => setDraft({ ...draft, fromCode: value })} /><Field label="Naar (code)" value={draft.toCode || ""} onChange={(value) => setDraft({ ...draft, toCode: value })} /><Field label="Vertrekdatum" type="date" value={draft.departureDate || ""} onChange={(value) => setDraft({ ...draft, departureDate: value })} /><Field label="Aankomstdatum" type="date" value={draft.arrivalDate || ""} onChange={(value) => setDraft({ ...draft, arrivalDate: value })} /><Field label="Vertrektijd" type="time" value={draft.departureTime || ""} onChange={(value) => setDraft({ ...draft, departureTime: value })} /><Field label="Aankomsttijd" type="time" value={draft.arrivalTime || ""} onChange={(value) => setDraft({ ...draft, arrivalTime: value })} /><Field label="Reserveringsnummer" value={draft.bookingReference || ""} onChange={(value) => setDraft({ ...draft, bookingReference: value })} /><Field label="Stoelen" value={draft.seat || ""} onChange={(value) => setDraft({ ...draft, seat: value })} /></div><button type="button" onClick={save} className="mt-4 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#174A7E] text-sm font-black text-white"><Save className="h-4 w-4" />Opslaan</button></div>}
      {!editing && <div className="mt-4"><AttachmentListControl attachments={flight.ticketPdfs} legacyAttachment={flight.ticketPdf} label="Ticket of bevestiging toevoegen" onChange={(ticketPdfs) => onUpdateFlight?.({ ...flight, ticketPdfs, ticketPdf: ticketPdfs[0] })} /></div>}
    </article>; })}</div>
    {!flights.length && !draft && <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center dark:border-slate-700 dark:bg-slate-900"><Plane className="mx-auto h-10 w-10 text-slate-300" /><h2 className="mt-3 font-black">Nog geen vluchten</h2></div>}
  </div>;
};
const Moment = ({ label, date, time }: { label: string; date?: string; time?: string }) => <div className="rounded-2xl bg-sky-50 p-3 dark:bg-sky-950/30"><p className="text-[10px] font-black uppercase tracking-wider text-sky-700">{label}</p><p className="mt-1 flex items-center gap-1 text-sm font-bold"><CalendarDays className="h-3.5 w-3.5" />{date || "Datum onbekend"}</p><p className="mt-1 flex items-center gap-1 text-xl font-black"><Clock3 className="h-4 w-4" />{time || "Nog invullen"}</p></div>;
const Info = ({ label, value }: { label: string; value?: string }) => <div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800/60"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-bold">{value || "Nog niet ingevuld"}</p></div>;
const Field = ({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) => <label className="text-xs font-bold text-slate-600 dark:text-slate-300">{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-normal dark:border-slate-700 dark:bg-slate-900" /></label>;
export default VluchtenView;
